services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    ports:
      - "${PORT_NODERED}:${PORT_NODERED}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`${SUBDOMAIN_NODERED}${DOMAIN}`)"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.services.nodered.loadbalancer.server.port=${PORT_NODERED}"
      - "traefik.http.routers.nodered.tls.certresolver=letsencrypt"
    volumes:
      - ./.node-red/data:/data
    networks:
      - backnet




