# https://kanzitelli.medium.com/deploying-postgresql-and-redis-behind-traefik-in-the-cloud-c8eade9b5874

services:
  redis:
    image: redis:8.6-trixie
    restart: always
    user: '0'
    container_name: redis
    expose:
      - 6379
    ports:
      - ${PORT_REDIS_UNSECURE}:6379
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - SKIP_FIX_PERMS=1
    volumes:
      - ./.redis/data:/data
      - ./.redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf --loglevel warning
    #labels:
      #- "traefik.enable=true"
      # routers
      #- "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      #- "traefik.tcp.routers.redis.entryPoints=redis"
      #- "traefik.tcp.routers.redis.service=redisservice"
      #- "traefik.tcp.routers.redis.tls.certresolver=letsencrypt"
      #- "traefik.tcp.routers.redis.tls=true"
       # services (needed for TCP)
      #- "traefik.tcp.services.redisservice.loadbalancer.server.port=6379"
    networks:
       - backnet
