services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    # ports:
    # - "${PORT_NODERED}:${PORT_NODERED}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-secure.rule=Host(`${SUBDOMAIN_NODERED}${DOMAIN}`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.services.api-secure.loadbalancer.server.port=${PORT_NODERED}"
      - "traefik.http.routers.api-secure.tls.certresolver=letsencrypt"
    volumes:
      - ./.node-red/data:/data
    networks:
      - backnet




